name: build CHAINSAWS
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: buttz
      - run: echo bla