name: build CHAINSAWS
on:
  push:
    branches: [$default-branch, shain/*]
  pull_request:
    branches: [$default-branch]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
